jobs:
  build_and_test: 
  
    executor: python/default 
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests #commands
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
